CREATE TABLE `user_email` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `activeflag` TINYINT(1) DEFAULT '1',
  `created` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `lastupdated` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` INT(11) DEFAULT NULL,
  `email` VARCHAR(225),
  `password` VARCHAR(225),
   PRIMARY KEY (`id`)
) ;